project:
  type: website
  output-dir: docs/

brand: _brand.yml

website:
  title: "BraVe Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - getstarted.qmd
      - documentation.qmd
      # - community.qmd

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
